;; ////////////////////////////////////////////////////////////////////////////////////////////////////
;; CEDET

;; //Kevin Tian: load file = load path append + load
;; (load-file "~/elisp/cedet-1.0pre7/common/cedet.el")
(setq load-path (append load-path (list "~/elisp/cedet-1.0pre7/common/")))

;; Error: let: ECB 2.40 - Error: ECB can only be used with cedet [1.0pre6, 1.0.9]! Please install it and restart Emacs!
;; conflict with ecb
;; (setq load-path (append load-path (list "~/elisp/cedet-1.1/common/")))
(load "cedet")

(global-ede-mode 1)                      ; Enable the Project management system


;;;;;;; Chose one of help mode
;; 2011_10_06 enabled
;; (semantic-load-enable-code-helpers)      ; Enable prototype help and smart completion 
;; (semantic-load-enable-guady-code-helpers)
;; enable all semantic feature
;; 2011_10_06 del
(semantic-load-enable-excessive-code-helpers)
;; (semantic-load-enable-all-exuberent-ctags-support)
;; //Kevin Tian: commen usage
;; (semantic-load-enable-code-helpers)
;; 2011_10_06 del
;; (semantic-load-enable-semantic-debugging-helpers)

(global-srecode-minor-mode 1)            ; Enable template insertion menu



;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; copy from my_ecb.el
(require 'semantic-gcc)

;; You can customize the semantic-idle-scheduler-idle-time variable to specify
;; idle time (in seconds), if you don't want to use default value.
(setq semantic-idle-scheduler-idle-time 2)


;; Customization of Semanticdb
;; If you use standard procedure for loading of Cedet, then Semanticdb will loaded automatically. Otherwise, you can load and enable
;; it with following commands:
(require 'semanticdb)
(global-semanticdb-minor-mode 1)

;; 
(require 'semantic-ia)


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; 2010_08_03
;; Integration with imenu
;; The Semantic package can be integrated with the imenu package. This enables the display of a menu with a list of functions,
;; variables, and other tags. To enable this feature you can either use semantic-load-enable-code-helpers, or, you need to add following
;; code into your initialization file:

(defun my-semantic-hook ()
(imenu-add-to-menubar "TAGS")
(semantic-show-parser-state-mode)
)
(add-hook 'semantic-init-hooks 'my-semantic-hook)

;; Besides this, Semanticdb can use databases generated by external utilities  gtags from GNU Global, ctags, ebrowse & cscope. To
;; activate this you can use following code:
;; x;; if you want to enable support for gnu global
(require 'semanticdb-global)
(semanticdb-enable-gnu-global-databases 'c-mode)
(semanticdb-enable-gnu-global-databases 'c++-mode)

;; enable ctags for some languages:
;; Unix Shell, Perl, Pascal, Tcl, Fortran, Asm
(semantic-load-enable-primary-exuberent-ctags-support)

(setq global-semantic-tag-folding-mode t)


;; speedbar
(add-hook 'speedbar-load-hook (lambda () (require 'semantic-sb)))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; function define
;; 2010_08_05
;;; Auto expand

(defun my-indent-or-complete ()

   (interactive)

   (if (looking-at "\\>")

          (hippie-expand nil)

          (indent-for-tab-command))

)


(autoload 'senator-try-expand-semantic "senator")

(setq hippie-expand-try-functions-list

          '(

              senator-try-expand-semantic

                   try-expand-dabbrev

                   try-expand-dabbrev-visible

                   try-expand-dabbrev-all-buffers

                   try-expand-dabbrev-from-kill

                   try-expand-list

                   try-expand-list-all-buffers

                   try-expand-line

        try-expand-line-all-buffers

        try-complete-file-name-partially

        try-complete-file-name

        try-expand-whole-kill

        )

)

;;;;; 2011_08_18

(setq-mode-local c-mode
								 semanticdb-find-default-throttle
								 '(project unloaded system recursive))

(require 'semantic-sb)



(global-ede-mode 1)

;; ;;;;; 
;; Cscope Setting for EDE
;; (setq ede-locate-setup-options
;; 			'(ede-locate-cscope
;; 				ede-locate-base))


;; could not use this option
;; (semanticdb-enable-cscope-databases)

;;;;;
(require 'semanticdb)
(global-semanticdb-minor-mode 1)

;; 2011_08_22
;; F2 set bookmark
;; C-F2 navigate forward
;; S-F2 navigate backward
;; C-S-F2 clear all bookmark
;; depend on cedet lib
(enable-visual-studio-bookmarks)
